export class ItemConfig {
    public static itemConfig = {
        //冲刺
        item_cc:{
            name:"item_cc",
            textureName:"item_cc",
            effectTexture:"fly_buff0"
        },
        //磁铁
        item_xts:{
            name:"item_xts",
            textureName:"item_xts",
            effectTexture:"fly_buff1"
        },
        //能量护盾
        item_protect:{
            name:"item_protect",
            textureName:"item_protect",
            effectTexture:"fly_buff2"
        },
        //火力全开（影子）
        item_shadow:{
            name:"item_shadow",
            textureName:"item_powerUp",
            effectTexture:"fly_buff3"
        },
        //双倍攻击（二条）
        item_double:{
            name:"item_double",
            textureName:"item_double",
            effectTexture:"fly_buff4"
        },
        //10金币
        item_coin:{
            name:"item_coin",
            textureName:"item_coin",
            gold:10,
            effectTexture:"fly_gold_10"
        },
        //50金币
        item_red:{
            name:"item_red",
            textureName:"item_red",
            gold:50,
            effectTexture:"fly_gold_50"
        },
        //100金币
        item_green:{
            name:"item_green",
            textureName:"item_green",
            gold:100,
            effectTexture:"fly_gold_100"
        }
    };
}