export class ItemConfig {
    public static itemConfig = {
        //冲刺
        item_cc:{
            name:"item_cc",
            textureName:"item_cc",
            presetCount:2,
            effectTexture:"#fly_buff0.png"
        },
        //二条
        item_doubleFire:{
            name:"item_doubleFire",
            textureName:"item_up_skill",
            presetCount:2,
            effectTexture:"#fly_buff4.png"
        },
        //磁铁
        item_xts:{
            name:"item_xts",
            textureName:"item_xts",
            presetCount:2,
            effectTexture:"#fly_buff1.png"
        },
        //炸弹
        item_down_skill:{
            name:"item_down_skill",
            textureName:"item_down_skill",
            presetCount:2,
            effectTexture:"#fly_buff5.png"
        },
        //10金币
        item_coin:{
            name:"item_coin",
            textureName:"item_coin",
            presetCount:20,
            gold:10
        },
        //50金币
        item_red:{
            name:"item_red",
            textureName:"item_red",
            presetCount:7,
            gold:50
        },
        //100金币
        item_green:{
            name:"item_green",
            textureName:"item_green",
            presetCount:5,
            gold:100
        }
    };
}